sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

#sonata_user:
#    manager_type: orm # can be orm or mongodb
#    class:
#        user: App\Application\Sonata\UserBundle\Entity\User
#        group: App\Application\Sonata\UserBundle\Entity\Group


sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.user.block.menu:
        sonata.user.block.account:
        sonata.block.service.text:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
